// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportPlanner.Infrastructure.Data;

#nullable disable

namespace TransportPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(TransportPlannerDbContext))]
    partial class TransportPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DayPlanLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraWorkMinutesAllDrivers")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DayPlanLocks");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultServiceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<int>("ErpId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxWorkMinutesPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(480);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("StartAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ErpId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("ToolId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DriverAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("EndMinuteOfDay")
                        .HasColumnType("int");

                    b.Property<int>("StartMinuteOfDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Date")
                        .IsUnique();

                    b.ToTable("DriverAvailabilities", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DriverDayOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraWorkMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverDayOverrides");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DriverServiceType", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DriverId", "ServiceTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("DriverServiceTypes", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.LearnedTravelStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgMinutesPerKm")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("AvgStopServiceMinutes")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("BucketEndHour")
                        .HasColumnType("int");

                    b.Property<int>("BucketStartHour")
                        .HasColumnType("int");

                    b.Property<int>("DayType")
                        .HasColumnType("int");

                    b.Property<decimal>("DistanceBandKmMax")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("DistanceBandKmMin")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "DayType", "BucketStartHour", "BucketEndHour", "DistanceBandKmMin", "DistanceBandKmMax")
                        .IsUnique();

                    b.ToTable("LearnedTravelStats", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.PlanningCluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CentroidLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CentroidLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ClusterDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("LocationCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalServiceMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlanningClusters");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.PlanningClusterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlanningClusterId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanningClusterId");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("PlanningClusterItems");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RegionSpeedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgMinutesPerKm")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("BucketEndHour")
                        .HasColumnType("int");

                    b.Property<int>("BucketStartHour")
                        .HasColumnType("int");

                    b.Property<int>("DayType")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "DayType", "BucketStartHour", "BucketEndHour")
                        .IsUnique();

                    b.ToTable("RegionSpeedProfiles", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("EndAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("float");

                    b.Property<bool>("EndIsHotel")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("StartAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<bool>("StartIsHotel")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalKm")
                        .HasColumnType("real");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("WeightTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("WeightTemplateId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteChangeNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("RouteVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("RouteVersionId");

                    b.ToTable("RouteChangeNotifications", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PlannerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteStopId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("RouteStopId");

                    b.ToTable("RouteMessages", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrivalUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDepartureUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActualServiceMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<string>("IssueCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<bool>("ManualAdded")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlanningClusterId")
                        .HasColumnType("int");

                    b.Property<int>("ProofStatus")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceLocationId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StopType")
                        .HasColumnType("int");

                    b.Property<float>("TravelKmFromPrev")
                        .HasColumnType("real");

                    b.Property<int>("TravelMinutesFromPrev")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanningClusterId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteStopEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteStopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteStopId");

                    b.ToTable("RouteStopEvents", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RouteVersions", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverInstruction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExtraInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErpId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PriorityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ErpId")
                        .IsUnique();

                    b.HasIndex("ToolId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "Status", "DueDate");

                    b.HasIndex("ServiceTypeId", "Status", "DueDate");

                    b.ToTable("ServiceLocations", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationConstraint", b =>
                {
                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxVisitDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinVisitDurationMinutes")
                        .HasColumnType("int");

                    b.HasKey("ServiceLocationId");

                    b.ToTable("ServiceLocationConstraints", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId", "Date");

                    b.ToTable("ServiceLocationExceptions", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationOpeningHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CloseTime2")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OpenTime2")
                        .HasColumnType("time");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId", "DayOfWeek");

                    b.ToTable("ServiceLocationOpeningHours", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ServiceLocationOwners", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("ServiceTypes", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.SystemCostSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("FuelCostPerKm")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PersonnelCostPerHour")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("[OwnerId] IS NOT NULL");

                    b.ToTable("SystemCostSettings", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.TravelTimeRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BboxMaxLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("BboxMaxLon")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("BboxMinLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("BboxMinLon")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TravelTimeRegions", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.WeightTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeType")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WeightDate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DueCostCapPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DetourCostCapPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DetourRefKmPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LateRefMinutesPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WeightDistance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WeightOvertime")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WeightTravelTime")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "OwnerId", "ServiceTypeId");

                    b.ToTable("WeightTemplates", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.WeightTemplateLocationLink", b =>
                {
                    b.Property<int>("WeightTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.HasKey("WeightTemplateId", "ServiceLocationId");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("WeightTemplateLocationLinks", (string)null);
                });

            modelBuilder.Entity("TransportPlanner.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TransportPlanner.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TransportPlanner.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TransportPlanner.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DriverAvailability", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Driver", "Driver")
                        .WithMany("Availabilities")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DriverDayOverride", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.DriverServiceType", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Driver", "Driver")
                        .WithMany("DriverServiceTypes")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("DriverServiceTypes")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.LearnedTravelStats", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.TravelTimeRegion", "Region")
                        .WithMany("LearnedStats")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.PlanningClusterItem", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.PlanningCluster", "PlanningCluster")
                        .WithMany("Items")
                        .HasForeignKey("PlanningClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningCluster");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.SystemCostSettings", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocationOwner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceType", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocationOwner", "Owner")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RegionSpeedProfile", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.TravelTimeRegion", "Region")
                        .WithMany("SpeedProfiles")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.Route", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.WeightTemplate", "WeightTemplate")
                        .WithMany()
                        .HasForeignKey("WeightTemplateId");

                    b.Navigation("Driver");

                    b.Navigation("WeightTemplate");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteChangeNotification", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.Route", "Route")
                        .WithMany("ChangeNotifications")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.RouteVersion", "RouteVersion")
                        .WithMany("Notifications")
                        .HasForeignKey("RouteVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("RouteVersion");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteMessage", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.Route", "Route")
                        .WithMany("Messages")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.RouteStop", "RouteStop")
                        .WithMany()
                        .HasForeignKey("RouteStopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("RouteStop");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.PlanningCluster", "PlanningCluster")
                        .WithMany()
                        .HasForeignKey("PlanningClusterId");

                    b.HasOne("TransportPlanner.Domain.Entities.Route", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany()
                        .HasForeignKey("ServiceLocationId");

                    b.Navigation("PlanningCluster");

                    b.Navigation("Route");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteStopEvent", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.RouteStop", "RouteStop")
                        .WithMany("Events")
                        .HasForeignKey("RouteStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteStop");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteVersion", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.Route", "Route")
                        .WithMany("Versions")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationConstraint", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithOne("Constraint")
                        .HasForeignKey("TransportPlanner.Domain.Entities.ServiceLocationConstraint", "ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationException", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany("Exceptions")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationOpeningHours", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany("OpeningHours")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.WeightTemplateLocationLink", b =>
                {
                    b.HasOne("TransportPlanner.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany("WeightTemplateLinks")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportPlanner.Domain.Entities.WeightTemplate", "WeightTemplate")
                        .WithMany("LocationLinks")
                        .HasForeignKey("WeightTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");

                    b.Navigation("WeightTemplate");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("DriverServiceTypes");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocationOwner", b =>
                {
                    b.Navigation("ServiceTypes");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.PlanningCluster", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.Route", b =>
                {
                    b.Navigation("ChangeNotifications");

                    b.Navigation("Messages");

                    b.Navigation("Stops");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteStop", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.RouteVersion", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceLocation", b =>
                {
                    b.Navigation("Constraint");

                    b.Navigation("Exceptions");

                    b.Navigation("OpeningHours");

                    b.Navigation("WeightTemplateLinks");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("DriverServiceTypes");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.TravelTimeRegion", b =>
                {
                    b.Navigation("LearnedStats");

                    b.Navigation("SpeedProfiles");
                });

            modelBuilder.Entity("TransportPlanner.Domain.Entities.WeightTemplate", b =>
                {
                    b.Navigation("LocationLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
